version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: agrodigital
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
